blueprint:
  name: Set Timer For X Minutes
  description: Set timer for device to turn off.
  domain: automation
  input:
    entity_1:
      name: Entity
      selector:
        entity: {}
    time_1:
      name: Set Time
      default: 5
      selector:
        number:
          min: 1.0
          max: 720.0
          unit_of_measurement: min
          mode: slider
          step: 1.0
mode: single
max_exceeded: silent
  
trigger:
- platform: state
  entity_id: !input entity_1
  to: 'on'
  for:
    minutes: !input time_1
condition: []
action:
- service: homeassistant.turn_off
  data: {}
  target:
    entity_id: !input entity_1
